template: true
valuesFilePath: ./values.yml

resources:
  - name: git_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory.name }}


pipelines:

  - name: demo_maven
    steps:
      - name: mvn_package
        type: MvnBuild
        configuration:
          mvnCommand: clean package -DskipTests
          deployerSnapshotRepo: {{ .Values.snapshotRepo }}
          deployerReleaseRepo: {{ .Values.releaseRepo }}
#          configFileLocation: .jfrog-pipelines/config
#          configFileName: settings.xml
#          sourceLocation: .
          inputResources:
            - name: git_repo
          integrations:
            - name: {{ .Values.artifactory.name }}

      - name: publish_mvn_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: true
          inputSteps:
            - name: mvn_package
          outputResources:
            - name: mvn_build_info

      - name: security_scan
        type: XrayScan
        configuration:
          failOnScan: false
          inputResources:
            - name: mvn_build_info

      - name: mvn_test
        type: MvnBuild
        configuration:
          mvnCommand: test
          deployerSnapshotRepo: {{ .Values.snapshotRepo }}
          deployerReleaseRepo: {{ .Values.releaseRepo }}
#          configFileLocation: .jfrog-pipelines/config/settings.xml
#          sourceLocation: .
          inputResources:
            - name: git_repo
          integrations:
            - name: {{ .Values.artifactory.name }}
          inputSteps:
            - name: security_scan


#      - name: build_docker_image
#        type: DockerBuild
#        configuration:
#          dockerFileLocation: .
#          dockerFileName: Dockerfile
#          dockerImageName: {{ .Values.docker.imageName }}
#          dockerImageTag: ${run_number}
#          inputResources:
#            - name: mvn_package
#            - name: git_repo
#          integrations:
#            - name: {{ .Values.artifactory.name }}
#
#      - name: push_docker_image
#        type: DockerPush
#        configuration:
#          forceXrayScan: true
#          integrations:
#            - name: {{ .Values.artifactory.name }}
#          inputSteps:
#            - name: build_docker_image
#          outputResources:
#            - name: docker_build_info
#
#      - name: publish_docker_build
#        type: PublishBuildInfo
#        configuration:
#          forceXrayScan: false
#          inputSteps:
#            - name: push_docker_image
#          outputResources:
#            - name: docker_build_info